//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public Nullable<System.Guid> OfficeId { get; set; }
        public string Code { get; set; }
        public byte Status { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime LastLogin { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Theme { get; set; }
        public byte Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Question1 { get; set; }
        public string Answer1 { get; set; }
        public string Question2 { get; set; }
        public string Answer2 { get; set; }
        public System.Guid UpdatedByUserId { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<byte> EmploymentStatus { get; set; }
        public string PageLength { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
    }
}
