//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPCAnnexureIIIDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid AnnexureIIIId { get; set; }
        public System.Guid DenominationsId { get; set; }
        public Nullable<int> UnsortedCashCollected { get; set; }
        public Nullable<int> UnsortedCashCollectedValue { get; set; }
        public Nullable<int> FITReIssuable { get; set; }
        public Nullable<int> FITReIssuableValue { get; set; }
        public Nullable<int> UnfitSoiled { get; set; }
        public Nullable<int> UnfitSoiledValue { get; set; }
        public Nullable<int> MismatchDefacedZero { get; set; }
        public Nullable<int> MismatchDefacedZeroValue { get; set; }
        public Nullable<int> CounterfeitNotes { get; set; }
        public Nullable<int> CounterfeitNotesValue { get; set; }
        public Nullable<int> NetExcess { get; set; }
        public Nullable<int> NetExcessValue { get; set; }
        public Nullable<int> NetShortage { get; set; }
        public Nullable<int> NetShortageValue { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
    
        public virtual CPCAnnexureIII CPCAnnexureIII { get; set; }
    }
}
