//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPCAnnexureIII
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPCAnnexureIII()
        {
            this.CPCAnnexureIIIDetails = new HashSet<CPCAnnexureIIIDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CashCollectedFromId { get; set; }
        public System.DateTime AnnexureIIIDate { get; set; }
        public Nullable<int> TotalBundlesCollected { get; set; }
        public Nullable<int> SrNo { get; set; }
        public Nullable<int> TotalCashCollected { get; set; }
        public Nullable<System.DateTime> DateOfCashReturn { get; set; }
        public Nullable<int> TotalBundlesReturn { get; set; }
        public Nullable<int> TotalLoosePacketsNotesReturned { get; set; }
        public Nullable<int> TotalCashReturned { get; set; }
        public Nullable<int> ShipmentReceiptNo { get; set; }
        public Nullable<System.Guid> CashReceivedByCPCStaffA { get; set; }
        public Nullable<System.Guid> CashReceivedByCPCStaffB { get; set; }
        public Nullable<System.Guid> CashHandedOverByCITStaffAId { get; set; }
        public Nullable<System.Guid> CashHandedOverByCITStaffBId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public byte Status { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPCAnnexureIIIDetail> CPCAnnexureIIIDetails { get; set; }
        public virtual CPCProjectBranch CPCProjectBranch { get; set; }
    }
}
