//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPCAnnexureI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPCAnnexureI()
        {
            this.CPCAnnexureIDetails = new HashSet<CPCAnnexureIDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> SrNo { get; set; }
        public Nullable<System.Guid> CashHandedOverCPCStaffAId { get; set; }
        public Nullable<System.Guid> CashHandedOverCPCStaffBId { get; set; }
        public Nullable<System.Guid> CashHandedOverCITStaffAId { get; set; }
        public Nullable<System.Guid> CashHandedOverCITStaffBId { get; set; }
        public Nullable<System.Guid> SignatureCPCHandingOverCashAId { get; set; }
        public Nullable<System.Guid> SignatureCPCHandingOverCashBId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public System.DateTime DateOfCollection { get; set; }
        public byte Status { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.Guid> OrderBookingId { get; set; }
        public string CashHandedOverCPCStaffACNIC { get; set; }
        public string CashHandedOverCPCStaffBCNIC { get; set; }
        public string CashHandedOverCITStaffACNIC { get; set; }
        public string CashHandedOverCITStaffBCNIC { get; set; }
        public string SignatureCPCHandingOverCashACNIC { get; set; }
        public string SignatureCPCHandingOverCashBCNIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPCAnnexureIDetail> CPCAnnexureIDetails { get; set; }
        public virtual CPCOrderBooking CPCOrderBooking { get; set; }
    }
}
