//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPCCashProcessingHouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPCCashProcessingHouse()
        {
            this.CPCProjectBranches = new HashSet<CPCProjectBranch>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public string CityName { get; set; }
    
        public virtual CPCProject CPCProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPCProjectBranch> CPCProjectBranches { get; set; }
    }
}
