//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPCCashInTransitChild
    {
        public System.Guid CashInTransitId { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<int> SealNumber { get; set; }
        public string Item { get; set; }
        public Nullable<int> Value { get; set; }
        public string PartialDelivery { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual CPCCashInTransit CPCCashInTransit { get; set; }
    }
}
