//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPCSortedCashDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid SortedCashId { get; set; }
        public Nullable<int> NumberOfPiecesReIssuable { get; set; }
        public Nullable<int> NumberOfPiecesSoiled { get; set; }
        public Nullable<int> NumberOfPiecesMachineRejected { get; set; }
        public Nullable<int> NumberOfPiecesCounterFeit { get; set; }
        public Nullable<int> NumberOfPiecesMismatch { get; set; }
        public Nullable<int> TotalValue { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<int> AssignedBundles { get; set; }
        public Nullable<int> NumberOfPiecesClaim { get; set; }
        public Nullable<int> NumberOfPiecesDesecrated { get; set; }
        public Nullable<int> NumberOfPiecesShort { get; set; }
        public Nullable<int> NumberOfPiecesExcess { get; set; }
        public Nullable<int> NumberOfPiecesUnprocess { get; set; }
        public Nullable<int> AssignedAmount { get; set; }
        public Nullable<System.Guid> SorterId { get; set; }
    
        public virtual CPCSortedCash CPCSortedCash { get; set; }
    }
}
