//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPCVaultConsolidatedBundle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPCVaultConsolidatedBundle()
        {
            this.CPCVaultConsolidatedBundlesDetails = new HashSet<CPCVaultConsolidatedBundlesDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrderBookingId { get; set; }
        public System.Guid DenominationId { get; set; }
        public System.Guid ConsolidatedDetailsId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
    
        public virtual CPCDenomination CPCDenomination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPCVaultConsolidatedBundlesDetail> CPCVaultConsolidatedBundlesDetails { get; set; }
        public virtual CPCVaultConsolidatedDetail CPCVaultConsolidatedDetail { get; set; }
    }
}
