//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPCVaultConsolidatedBundlesDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid ConsolidatedBundlesId { get; set; }
        public int NumberOfBundles { get; set; }
        public int Amount { get; set; }
        public Nullable<System.Guid> SorterId { get; set; }
    
        public virtual CPCVaultConsolidatedBundle CPCVaultConsolidatedBundle { get; set; }
        public virtual CPCEmployee CPCEmployee { get; set; }
    }
}
