//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vew_VaultCustodian
    {
        public System.Guid Id { get; set; }
        public long SerialNumber { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid ProjectBranchId { get; set; }
        public Nullable<int> TotalNumberBundles { get; set; }
        public long TotalBalance { get; set; }
        public Nullable<byte> Status { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.Guid> OrderBookingId { get; set; }
        public System.Guid CPCUnsortedCashDetailsId { get; set; }
        public System.Guid DenominationId { get; set; }
        public Nullable<int> DenominationTitle { get; set; }
        public int NumberOfBundles { get; set; }
        public int TotalValue { get; set; }
        public string SealNo { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public string CityName { get; set; }
        public Nullable<System.Guid> SupervisorId { get; set; }
        public System.Guid VaultCustodianId { get; set; }
        public string SupervisorName { get; set; }
    }
}
