//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vew_Orderbookings
    {
        public System.Guid Id { get; set; }
        public int OrderNo { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public System.Guid CPCOrderBookingDetailsId { get; set; }
        public Nullable<System.Guid> ProjectBranchId { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public Nullable<System.Guid> DenominationId { get; set; }
        public Nullable<int> DenominationTitle { get; set; }
        public Nullable<System.Guid> CashProcessingCellId { get; set; }
        public string CashProcessingCellTitle { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public string CPCProjectName { get; set; }
        public Nullable<int> NoOfBundles { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> ApprovedById { get; set; }
        public string ApprovedByName { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public byte Status { get; set; }
        public Nullable<byte> CashCollectionPoint { get; set; }
        public Nullable<byte> CashDeliveryPoint { get; set; }
        public Nullable<System.Guid> CollectionBranchId { get; set; }
        public string CollectionBranchName { get; set; }
        public Nullable<System.Guid> DeliveryBranchId { get; set; }
        public string DeliveryBranchName { get; set; }
        public Nullable<System.Guid> BilledBranchId { get; set; }
        public string BilledBranchName { get; set; }
        public Nullable<System.Guid> VehicleId { get; set; }
        public string VehicleNumber { get; set; }
    }
}
